name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd actix-web && cargo build --verbose
    - name: Run tests
      run: cd actix-web && cargo test --verbose
